#!/bin/bash

# Resource groups list, eg. pods
group_resources=()

# Machine/Node Resources
group_resources+=(nodes)

# Resource list
resources=()

# Openstack namespace
resources+=(ns/openstack)

# Install-related namespaces
resources+=(ns/openshift-operator-lifecycle-manager ns/openshift-marketplace)

# CNV namespace
resources+=(ns/openshift-cnv)

# SRIOV namespace
resources+=(ns/sriov-network-operator)

# Install-related resources
resources+=(catalogsource clusterserviceversion)

# CNV-related resources
resources+=(virtualmachines virtualmachineinstances datavolumes)

# Metal3-related resources
resources+=(baremetalhosts provisionings)

# Networking resources
resources+=(nodenetworkstates nodenetworkconfigurationenactments network-attachment-definitions nodenetworkconfigurationpolicies)

# SRIOV resources
resources+=(sriovnetworks sriovnetworknodestates sriovnetworknodepolicies)

# Storage resource
resources+=(storageclasses persistentvolumeclaims persistentvolumes)

# Run the collection of resources using must-gather
for resource in "${resources[@]}"; do
    echo "Inspecting resource ${resource}..."
    /usr/bin/oc adm inspect --dest-dir must-gather --all-namespaces "${resource}" &> /dev/null
done

filtered_group_resources=()
for gr in "${group_resources[@]}"
do
  /usr/bin/oc get "$gr" > /dev/null 2>&1
  if [[ "$?" -eq 0 ]]; then
    filtered_group_resources+=("$gr")
  fi
done
group_resources_text=$(IFS=, ; echo "${filtered_group_resources[*]}")
/usr/bin/oc adm inspect --dest-dir must-gather --rotated-pod-logs "${group_resources_text}"

# Operator subscription
/usr/bin/gather_sub

# CRDs
/usr/bin/gather_crds

# Openstack CRs
/usr/bin/gather_crs

# Operator pod and logs, as well as operator-generated native k8s resources and any associated logs (if applicable)
/usr/bin/gather_ospd

# TripleO-specific config not captured by previous gathers
# TODO?

# API services
/usr/bin/gather_apiservices

# Webhooks
/usr/bin/gather_webhooks

exit 0
